Starlite parameter types
starlite-api/starlite pull request #1140
Opened 2023-02-04 07:43 UTC by peterschutt

# PR Checklist

- [ ] Have you followed the guidelines in `CONTRIBUTING.rst`?
- [ ] Have you got 100% test coverage on new code?
- [ ] Have you updated the prose documentation?
- [ ] Have you updated the reference documentation?

2023-02-04 11:15 UTC, provinzkraut requested changes
Very nice changes overall!

- Docstrings need to be adjusted to the new types in various places
- The semantic handler decorators in `handlers/http.py` should have the same changes applied as the base handlers

2023-02-04 11:15 UTC, provinzkraut commented on starlite/controller.py
>      """A string key dictionary of arbitrary values that can be accessed in :class:`Guards <starlite.types.Guard>` or wherever
```suggestion
    """A string key mapping of arbitrary values that can be accessed in :class:`Guards <starlite.types.Guard>` or wherever
```

2023-02-04 11:15 UTC, provinzkraut commented on starlite/controller.py
>      """A dictionary that maps handler functions to status codes and/or exception types."""
```suggestion
    """A map of handler functions to status codes and/or exception types."""
```

2023-02-04 11:15 UTC, provinzkraut commented on starlite/controller.py
>      """A list of :class:`Guard <starlite.types.Guard>` callables."""
```suggestion
    """A sequence of :class:`Guard <starlite.types.Guard>` callables."""
```

2023-02-04 11:15 UTC, provinzkraut commented on starlite/controller.py
>      """A list of :class:`Middleware <starlite.types.Middleware>`."""
```suggestion
    """A sequence of :class:`Middleware <starlite.types.Middleware>`."""
```

2023-02-04 11:15 UTC, provinzkraut commented on starlite/controller.py
>      """A list of string tags that will be appended to the schema of all route handlers under the controller."""
```suggestion
    """A sequence of string tags that will be appended to the schema of all route handlers under the controller."""
```

2023-02-04 11:15 UTC, provinzkraut commented on starlite/controller.py
>      """A list of dictionaries that to the schema of all route handlers under the controller."""
```suggestion
    """A sequence of dictionaries that to the schema of all route handlers under the controller."""
```

2023-02-04 11:15 UTC, provinzkraut commented on starlite/handlers/asgi.py
> +        path: Optional[Union[str, Sequence[str]]] = None,
The types changed here also need to be changed in the docstring, but I can't comment on that

2023-02-04 11:15 UTC, provinzkraut commented on starlite/handlers/base.py
> +        path: Optional[Union[str, Sequence[str]]] = None,
The types changed here also need to be changed in the docstring, but I can't comment on that

2023-02-04 11:15 UTC, provinzkraut commented on starlite/handlers/http.py
> +        path: Optional[Union[str, Sequence[str]]] = None,
The types changed here also need to be changed in the docstring, but I can't comment on that

2023-02-04 11:15 UTC, provinzkraut commented on starlite/router.py
> +        dependencies: Optional[Mapping[str, Provide]] = None,
Docstrings need to be adjusted to the new types

2023-02-04 11:15 UTC, provinzkraut commented on starlite/testing/create_test_client.py
>  def create_test_client(
Docstrings need to be adjusted to the new types

2023-02-04 11:15 UTC, provinzkraut commented on starlite/utils/exception.py
> +        return exception_handlers[status_code]
```suggestion
    if status_code and (exception_handler := exception_handlers.get(status_code)):
        return exception_handler
``` 
?

2023-02-05 12:31 UTC, Goldziher approved these changes

2023-02-05 12:31 UTC, merged