Added from_config classmethod for Starlite
starlite-api/starlite pull request #1190
Opened 2023-02-12 20:34 UTC by wassafshahzad

# PR Checklist

- [x] Have you followed the guidelines in `CONTRIBUTING.rst`?
- [ ] Have you got 100% test coverage on new code?
- [ ] Have you updated the prose documentation?
- [ ] Have you updated the reference documentation?

### Which ticket is this PR associated with ?
Closes #1120 

### What does this PR do
This PR adds the following features
- Adds a configuration object in Starlite constructor
- Adds sane defaults in AppConfig
- Updates pre-commits to fix isort issue

### Background Context
This PR was accidently closed. Follow previous discussion [here](https://github.com/starlite-api/starlite/pull/1173)

2023-02-12 21:16 UTC, peterschutt requested changes
The type changes on the config object shouldn't be required and would be the source of the type issues that you've encountered when using the values from the config object in `Starlite.__init__()`

2023-02-12 21:16 UTC, peterschutt commented on starlite/app.py
> +            self.get_logger = self.logging_config.configure()  # type: ignore
I think the ignore is necessary here as we allow the logging config to be both `None` or `Empty` but `Empty` doesn't evaluate falsey, so at this point the config object could be `Empty` or a config object. It that is the case, the type error is correct and we shouldn't be ignoring it.

2023-02-12 21:16 UTC, peterschutt commented on starlite/config/app.py
> +    logging_config: Union["BaseLoggingConfig", "EmptyType", None]
```suggestion
    logging_config: Optional[Union["BaseLoggingConfig", "EmptyType"]]
```

2023-02-12 21:16 UTC, peterschutt commented on starlite/config/app.py
> +    parameters: Optional[ParametersMap] = None
```suggestion
    parameters: ParametersMap = {}
```

2023-02-12 21:16 UTC, peterschutt commented on starlite/config/app.py
> +    response_cookies: Optional["ResponseCookies"] = None
```suggestion
    response_cookies: ResponseCookies = []
```

2023-02-12 21:16 UTC, peterschutt commented on starlite/config/app.py
> +    response_headers: Optional["ResponseHeadersMap"] = None
```suggestion
    response_headers: ResponseHeadersMap = {}
```

2023-02-12 21:16 UTC, peterschutt commented on starlite/config/app.py
> +    route_handlers: "OptionalSequence[ControllerRouterHandler]" = None
```suggestion
    route_handlers: List[ControllerRouterHandler] = []
```

2023-02-12 21:16 UTC, peterschutt commented on starlite/config/app.py
> +    security: "OptionalSequence[SecurityRequirement]" = []
```suggestion
    security: List[SecurityRequirement] = []
```

2023-02-12 21:16 UTC, peterschutt commented on starlite/config/app.py
> +    static_files_config: "OptionalSequence[StaticFilesConfig]" = None
```suggestion
    static_files_config: List[StaticFilesConfig] = []
```

2023-02-12 23:59 UTC, peterschutt commented on starlite/config/app.py
> +    logging_config: Union["BaseLoggingConfig", "EmptyType", None]
I don't believe this isn't intended to be allowed to be both union `Empty` _and_ `Optional` on the config object. The possible `Empty` value is resolved away [here](https://github.com/starlite-api/starlite/blob/4cc867c0c5f49449b64932a391029b41b295b14c/starlite/app.py#L304).

2023-02-13 09:09 UTC, wassafshahzad commented on starlite/app.py
> +    Self,
> The type changes on the config object shouldn't be required and would be the source of the type issues that you've encountered when using the values from the config object in `Starlite.__init__()`

Thank you for informing me, I will revert those changes immediately, Any reason why those are required ? (I'm new to typing in python)

2023-02-13 09:11 UTC, wassafshahzad commented on starlite/app.py
>              self.register(route_handler)
I believe my changes in config objects types must have caused this issue

2023-02-13 09:12 UTC, wassafshahzad commented on starlite/config/app.py
> +    debug: bool = True
No clue about this, I thought debug by default would have been safer. I can set it to False

2023-02-13 09:32 UTC, wassafshahzad commented on starlite/config/app.py
> +    debug: bool = True
Sure, Will do,
BTW @provinzkraut, would you be able to guide me on @peterschutt [comment ](https://github.com/starlite-api/starlite/pull/1190#pullrequestreview-1294781156)

2023-02-15 13:24 UTC, provinzkraut approved these changes

2023-02-15 14:54 UTC, JacobCoffee approved these changes

2023-02-15 15:13 UTC, Goldziher commented
we are still missing documentation for this, @provinzkraut - should this be done in this scope? if not we can merge.

2023-02-15 15:13 UTC, Goldziher commented
@all-contributors add @wassafshahzad code

2023-02-15 15:15 UTC, wassafshahzad commented
Should I wait for @peterschutt review ?

2023-02-15 15:21 UTC, provinzkraut commented
> we are still missing documentation for this, @provinzkraut - should this be done in this scope? if not we can merge. 

I'll add this to the docs elsewhere

2023-02-15 16:41 UTC, peterschutt approved these changes

2023-02-15 17:39 UTC, merged