standardize exports
starlite-api/starlite pull request #1273
Opened 2023-03-04 13:05 UTC by Goldziher

# PR Checklist

- [x] Have you followed the guidelines in `CONTRIBUTING.rst`?
- [x] Have you got 100% test coverage on new code?
- [x] Have you updated the prose documentation?
- [x] Have you updated the reference documentation?

2023-03-04 13:37 UTC, Goldziher commented on starlite/config/logging.py
> +    "get_logger_placeholder",
```suggestion
```

2023-03-04 13:37 UTC, Goldziher commented on starlite/config/logging.py
> +    "get_default_handlers",
```suggestion
```

2023-03-04 13:38 UTC, Goldziher commented on starlite/config/logging.py
> +    "default_wrapper_class",
```suggestion
```

2023-03-04 13:38 UTC, Goldziher commented on starlite/config/logging.py
> +    "default_wrapper_class",
```suggestion
```

2023-03-04 13:38 UTC, Goldziher commented on starlite/config/logging.py
> +    "default_structlog_processors",
```suggestion
```

2023-03-04 13:38 UTC, Goldziher commented on starlite/config/logging.py
> +    "default_logger_factory",
```suggestion
```

2023-03-04 13:39 UTC, Goldziher commented on starlite/contrib/htmx/utils.py
> +    "get_trigger_event_headers",
```suggestion
```

2023-03-04 13:39 UTC, Goldziher commented on starlite/contrib/htmx/utils.py
> +    "get_retarget_header",
```suggestion
```

2023-03-04 13:40 UTC, Goldziher commented on starlite/contrib/htmx/utils.py
> +    "get_reswap_header",
```suggestion
```

2023-03-04 13:40 UTC, Goldziher commented on starlite/contrib/htmx/utils.py
> +    "get_replace_url_header",
```suggestion
```

2023-03-04 13:40 UTC, Goldziher commented on starlite/contrib/htmx/utils.py
> +    "get_refresh_header",
```suggestion
```

2023-03-04 13:40 UTC, Goldziher commented on starlite/contrib/htmx/utils.py
> +    "get_redirect_header",
```suggestion
```

2023-03-04 13:40 UTC, Goldziher commented on starlite/contrib/htmx/utils.py
> +    "get_push_url_header",
```suggestion
```

2023-03-04 13:40 UTC, Goldziher commented on starlite/contrib/htmx/utils.py
> +    "get_location_headers",
```suggestion
```

2023-03-04 13:40 UTC, Goldziher commented on starlite/contrib/htmx/utils.py
> +    "get_headers",
```suggestion
```

2023-03-04 13:41 UTC, Goldziher commented on starlite/contrib/sqlalchemy_1/config.py
> +    "default_before_send_handler",
```suggestion
```

2023-03-04 13:41 UTC, Goldziher commented on starlite/contrib/sqlalchemy_1/config.py
> +    "serializer",
```suggestion
```

2023-03-04 13:42 UTC, Goldziher commented on starlite/datastructures/url.py
> +    "make_absolute_url",
```suggestion
```

2023-03-04 13:42 UTC, Goldziher commented on starlite/dto.py
> +__all__ = ("DTO", "DTOFactory", "get_field_type")
```suggestion
__all__ = ("DTO", "DTOFactory")
```

2023-03-04 13:44 UTC, Goldziher commented on starlite/handlers/utils.py
> +__all__ = ("narrow_response_cookies", "narrow_response_headers")
these utils are used on different layers of the app - should they be here or in an "internal_utils.py" package? @starlite-api/maintainers

2023-03-04 13:45 UTC, Goldziher commented on starlite/middleware/csrf.py
> +__all__ = ("CSRFMiddleware", "generate_csrf_hash", "generate_csrf_token")
```suggestion
__all__ = ("CSRFMiddleware")
```

2023-03-04 14:48 UTC, Goldziher commented on starlite/contrib/opentelemetry/__init__.py
>  __all__ = ("OpenTelemetryConfig", "OpenTelemetryInstrumentationMiddleware", "get_route_details_from_scope")
```suggestion
__all__ = ("OpenTelemetryConfig", "OpenTelemetryInstrumentationMiddleware")
```

2023-03-05 08:14 UTC, peterschutt requested changes
For consistency, `CacheConfig`, `StaticFilesConfig`, and `TemplateConfig` should be moved into their owning namespace package/module, like `LoggingConfig`.

2023-03-05 08:14 UTC, peterschutt commented on starlite/types/file_types.py
> +__all__ = ["FileInfo", "FileSystemProtocol"]
should be tuple

2023-03-05 08:14 UTC, peterschutt commented on starlite/types/internal_types.py
> +__all__ = ["PathParameterDefinition"]
should be tuple

2023-03-05 08:14 UTC, peterschutt commented on starlite/utils/dataclass.py
> +__all__ = ["extract_dataclass_fields"]
should be tuple

2023-03-05 08:14 UTC, peterschutt commented on starlite/utils/deprecation.py
> +__all__ = ["deprecated", "warn_deprecation"]
shoudl be tuple

2023-03-05 08:14 UTC, peterschutt commented on starlite/utils/helpers.py
> +__all__ = ["Ref", "get_enum_string_value", "get_name", "unwrap_partial"]
should be tuple

2023-03-05 08:14 UTC, peterschutt commented on starlite/utils/path.py
> +__all__ = ["join_paths", "normalize_path"]
tuple

2023-03-05 08:14 UTC, peterschutt commented on starlite/utils/pydantic.py
> +__all__ = ["Config", "convert_dataclass_to_model", "convert_typeddict_to_model", "create_parsed_model_field"]
tuple

2023-03-05 08:14 UTC, peterschutt commented on starlite/utils/scope.py
> +__all__ = ["get_serializer_from_scope", "get_starlite_scope_state", "set_starlite_scope_state"]
tuple

2023-03-05 08:14 UTC, peterschutt commented on starlite/utils/sequence.py
> +__all__ = ["find_index", "unique"]
tuple

2023-03-05 08:14 UTC, peterschutt commented on starlite/utils/sync.py
> +__all__ = ["AsyncCallable", "AsyncIteratorWrapper", "as_async_callable_list", "async_partial", "is_async_callable"]
tuple

2023-03-05 08:14 UTC, peterschutt commented on starlite/utils/types.py
> +__all__ = ["annotation_is_iterable_of_type", "make_non_optional_union"]
tuple

2023-03-05 08:14 UTC, peterschutt commented on starlite/utils/compat.py
> +def py_39_safe_annotations(annotated: Any) -> Generator[Any, None, None]:
good catch!

2023-03-05 09:09 UTC, Goldziher commented on starlite/handlers/http_handlers/_utils.py
> +from typing import TYPE_CHECKING, Any, Sequence, cast
its what we have everywhere, we need to reconfigure the plugin to reject these first

2023-03-05 09:23 UTC, peterschutt approved these changes

2023-03-05 09:24 UTC, merged