update simple event emitter to use worker pattern
starlite-api/starlite pull request #1346
Opened 2023-03-18 19:53 UTC by Goldziher

# PR Checklist

- [x] Have you followed the guidelines in `CONTRIBUTING.rst`?
- [x] Have you got 100% test coverage on new code?
- [x] Have you updated the prose documentation?
- [x] Have you updated the reference documentation?

This PR updates the `EventEmitterBackend` abstract class and the `SimpleEventEmitter` concrete implementation to be more useful. I used the `Broadcaster` library from encode as a source of inspiration for the implementation, which uses the worker pattern. It appears to be working with trio, without an issue.

2023-03-19 17:29 UTC, provinzkraut requested changes

2023-03-19 17:29 UTC, provinzkraut commented on starlite/events/emitter.py
> +        """Worker that runs in a separate thread and continuously pulls events from asyncio queue.
```suggestion
        """Worker that runs in a separate task and continuously pulls events from asyncio queue.
```

it doesn't actually run in a separate thread

2023-03-19 17:29 UTC, provinzkraut commented on starlite/events/emitter.py
> +        while self._queue:
Should this not be `while True`?

2023-03-19 17:29 UTC, provinzkraut commented on starlite/events/emitter.py
> +
This is missing a `task_done()` call, since we need to `join` the queue on shutdown

2023-03-19 17:29 UTC, provinzkraut commented on starlite/events/emitter.py
> +        self._queue = None
```suggestion
        await self._queue.join()
        self._queue = None
```

2023-03-19 17:29 UTC, provinzkraut commented on starlite/events/emitter.py
> +            self._worker_task.cancel()
```suggestion
            self._worker_task.cancel()
            await self._worker_task
```

ensure the successful cancellation of the task

2023-03-20 12:27 UTC, Goldziher commented on starlite/events/emitter.py
> +import sniffio
i think this can go, no?

2023-03-20 12:28 UTC, Goldziher commented on starlite/events/emitter.py
> +            return
```suggestion
            return
            
```

2023-03-20 12:29 UTC, Goldziher commented on starlite/events/emitter.py
> +                raise ImproperlyConfiguredException("This backend only supports asyncio")
```suggestion
                raise ImproperlyConfiguredException("{type(self).__name__} only supports 'asyncio' based event loops")
```

2023-03-20 14:36 UTC, merged