implemented before_request and after_request hooks
starlite-api/starlite pull request #39
Opened 2022-01-17 18:46 UTC by Goldziher

2022-01-17 22:01 UTC, sondrelg commented
Could consider adding something like [this](https://github.com/ariebovenberg/slotscheck) as a pre-commit hook to help ensure the `__slots__` definitions don't get messed up.

2022-01-17 22:06 UTC, yudjinn requested changes

2022-01-17 22:06 UTC, yudjinn commented on starlite/handlers.py
> +        This mehtod is memoized so the computation occurs only once
small type, method

2022-01-18 01:18 UTC, ashwinvin requested changes

2022-01-18 01:18 UTC, ashwinvin commented on starlite/controller.py
> +        "response_class",
```suggestion
        "response_class",
        "guards",
```

2022-01-18 05:59 UTC, merged