Update flake8 plugins and clean typos
starlite-api/starlite pull request #599
Opened 2022-10-14 18:03 UTC by Goldziher

# PR Checklist

- [x] Have you followed the guidelines in `CONTRIBUTING.md`?
- [x] Have you got 100% test coverage on new code?
- [x] Have you updated the prose documentation?
- [x] Have you updated the reference documentation?

2022-10-14 19:45 UTC, jtraub commented on tests/plugins/piccolo_orm/piccolo_app.py
> +CURRENT_DIRECTORY = os.path.dirname(os.path.realpath(__file__))
Maybe we should use here pathlib for consistency?

2022-10-14 19:58 UTC, jtraub commented on tests/plugins/piccolo_orm/piccolo_app.py
> +CURRENT_DIRECTORY = os.path.dirname(os.path.realpath(__file__))
If we want to use pathlib only then `flake8-use-pathlib` seems to be a good addition to pre-commit hooks

Maybe, `flake8-use-fstring` is also worth checking out.

2022-10-14 20:52 UTC, cofin approved these changes

2022-10-15 03:12 UTC, peterschutt approved these changes

2022-10-15 06:21 UTC, seladb requested changes

2022-10-15 06:21 UTC, seladb commented on starlite/cache/memcached_cache_backend.py
> +        await self._memcached_client.set(key.encode(), self._config.serialize(value), expiration=expiration)
@Goldziher this change will not work with `aiomcache` - the parameter name is `exptime`:
https://github.com/aio-libs/aiomcache/blob/20f4b18d5fc4c54047ebaf6d28e6024d80d591e4/aiomcache/client.py#L252

2022-10-15 06:21 UTC, seladb commented on tests/caching/test_memcached_cache_backend.py
> +    async def set(self, key: bytes, value: bytes, expiration: int) -> None:
Let's change back to `exptime`?

2022-10-15 06:52 UTC, Goldziher commented on tests/caching/test_memcached_cache_backend.py
> +    async def set(self, key: bytes, value: bytes, expiration: int) -> None:
Ofc

2022-10-15 14:24 UTC, infohash approved these changes

2022-10-15 19:35 UTC, seladb approved these changes

2022-10-15 20:47 UTC, merged