Add `AbstractMiddleware` class.
starlite-api/starlite pull request #729
Opened 2022-10-31 18:11 UTC by Goldziher

# PR Checklist

- [x] Have you followed the guidelines in `CONTRIBUTING.md`?
- [x] Have you got 100% test coverage on new code?
- [ ] Have you updated the prose documentation?
- [x] Have you updated the reference documentation?

This PR adds an `AbstractMiddleware`

2022-10-31 18:39 UTC, infohash approved these changes

2022-10-31 19:27 UTC, jtraub approved these changes

2022-11-01 09:03 UTC, provinzkraut requested changes

2022-11-01 09:03 UTC, provinzkraut commented on tests/middleware/test_base_middleware.py
> +def test_exclude_by_pattern() -> None:
This should test for passing multiple patterns in a list as well

2022-11-02 08:17 UTC, provinzkraut requested changes
LGTM, except I definitely prefer @peterschutt's `__init_subclass__` implementation in #736

2022-11-02 09:02 UTC, provinzkraut approved these changes

2022-11-02 09:03 UTC, peterschutt approved these changes

2022-11-02 14:26 UTC, merged